apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-backend

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: host

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: port

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: database

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: username

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: password

          resources:
{{ toYaml .Values.resources | indent 12 }}
