apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: backend-db-secret
  namespace: default

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: backend-db-secret
    creationPolicy: Owner

  data:
    - secretKey: host
      remoteRef:
        key: eks-devops-project/rds-credentials
        property: host

    - secretKey: port
      remoteRef:
        key: eks-devops-project/rds-credentials
        property: port

    - secretKey: database
      remoteRef:
        key: eks-devops-project/rds-credentials
        property: database

    - secretKey: username
      remoteRef:
        key: eks-devops-project/rds-credentials
        property: username

    - secretKey: password
      remoteRef:
        key: eks-devops-project/rds-credentials
        property: password
