replicaCount: 2

image:
  repository: 672937918836.dkr.ecr.ap-south-1.amazonaws.com/eks-devops-project-backend
  tag: 673b8b442b7fa66c0e4fae5beb9f4bbfc890cd32
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

containerPort: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
