replicaCount: 2

image:
  repository: 672937918836.dkr.ecr.ap-south-1.amazonaws.com/eks-devops-project-backend
  tag: efa0d3f85450b23352d3de021a4cb43147cd564c
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

containerPort: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
