replicaCount: 2

image:
  repository: 672937918836.dkr.ecr.ap-south-1.amazonaws.com/eks-devops-project-frontend
  tag: 673b8b442b7fa66c0e4fae5beb9f4bbfc890cd32
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

containerPort: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "500m"
    memory: "256Mi"
